# GitHub Personal Access Token設定
[github]
token = "YOUR_GITHUB_TOKEN_HERE"
default_repo = "jointresearchshun-tech/hologram-storage"

# Google Colab ngrok URL設定  
[colab]
server_1_name = "Colab Server 1"
server_1_url = "YOUR_NGROK_URL_HERE"

# 追加設定（オプション）
[settings]
auto_refresh = true
max_file_size = "100MB"
